eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9095/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: GestionCours
          uri: lb://GestionCours
          predicates:
            - Path=/cours/**
          filters:
            - RewritePath=/cours/(?<path>.*), /${path}

        - id: GestionProfesseur
          uri: lb://GestionProfesseur
          predicates:
            - Path=/prof/**
          filters:
            - RewritePath=/prof/(?<path>.*), /${path}
